spring.application.name=recommendation-service

# Read-only a Config H2 database
application.recommendations-db.url=jdbc:h2:file:./src/main/resources/transaction;DB_CLOSE_ON_EXIT=FALSE

# Disable automatic initialization of the Spring Boot database
spring.sql.init.mode=never


# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Application Port
server.port=8080
