#============================================================
#BASIC APPLICATION SETTINGS
#============================================================

spring.application.name=recommendation-service

# Server settings
server.port=${SERVER_PORT:8080}

# Active profiles (can be overridden by SPRING_PROFILES_ACTIVE env variable)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

#============================================================

# Config H2 Read-only database
application.recommendations-db.url=${H2_DATABASE_URL:jdbc:h2:file:./src/main/resources/transaction;DB_CLOSE_ON_EXIT=FALSE}
application.recommendations-db.driver-class-name=org.h2.Driver

# Disable automatic initialization of the Spring Boot database
spring.sql.init.mode=never

# H2 Console settings
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

#============================================================

# Config Read-Write PostgreSQL database
spring.datasource.driver-class-name=org.postgresql.Driver

# URL, username, password will be migration from .env
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/dynamic_rules}
spring.datasource.username=${POSTGRES_USERNAME:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:password}


# Connection pool settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

#============================================================

# JPA & HIBERNATE settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#============================================================

#Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/dynamic-rules/changelog-master.yaml

#============================================================

# Logging Configuration
logging.level.org.skypro.bank.star.recommendations_service=${LOG_LEVEL:INFO}
logging.level.org.springframework.jdbc.core=WARN
logging.level.org.hibernate=WARN
logging.level.org.liquibase=INFO

#============================================================

# Cache Configuration
cache.size.max=${CACHE_SIZE_MAX:1000}
cache.ttl.hours=${CACHE_TTL_HOURS:24}
