#============================================================
# DEVELOP SETTINGS
#============================================================

# Logging settings
logging.level.org.skypro.bank.star.recommendations_service=${LOG_LEVEL:DEBUG}
logging.level.org.hibernate.SQL=${LOG_LEVEL:DEBUG}
logging.level.org.liquibase=INFO

# JPA & HIBERNATE settings
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# Cache Configuration
cache.size.max=${CACHE_SIZE_MAX:1000}
cache.ttl.hours=${CACHE_TTL_HOURS:24}