#============================================================
# DEVELOP SETTINGS
#============================================================


# Logging Configuration
logging.level.root=${LOG_LEVEL:INFO}
logging.level.org.skypro.bank.star=${APP_LOG_LEVEL:DEBUG}

logging.level.org.springframework.jdbc.core=${APP_LOG_LEVEL:WARN}
logging.level.org.hibernate=${SQL_LOG_LEVEL:WARN}
logging.level.org.liquibase=${SQL_LOG_LEVEL:INFO}

logging.level.org.springframework.web=${WEB_LOG_LEVEL:DEBUG}


# JPA & HIBERNATE settings
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# Cache Configuration
cache.size.max=${CACHE_SIZE_MAX:1000}
cache.ttl.hours=${CACHE_TTL_HOURS:24}